name: deploy

on:
  push:
    branches:
      - hexo

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - name: Setup Pandoc environment
        run: |
          apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install --no-install-recommends pandoc
      - name: Setup Hexo environment
        run: |
          npm install -g hexo-cli
      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Deploy Blog
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "SignorinoY"
          git config --global user.email "meetziyang@gmail.com"
          hexo g -d