name: deploy

on:
  push:
    branches:
      - hexo

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - name: Setup pandoc environment
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.9/pandoc-2.9-1-amd64.deb
          sudo dpkg -i ./pandoc-2.9-1-amd64.deb
      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Deploy Blog
        id: deploy
        uses: sma11black/hexo-action@v1.0.4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}